services:
  - type: web
    name: launchpad
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://launchpad-6x1v.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
